### ISSUE TITLE
Still usable?

### ISSUE THREAD

**Issue by WRtux** [xiami2021/backup#10]
2 月 7 日中午开始已无法通过解析访问 emumo.xiami.com 了（应该是上游服务器被关闭）。真还能使用吗？

**Comment by postxiami** [comment]
部分功能无法使用 按照提示做

**Comment by WRtux** [comment]
OK. 目前看来可以正常获取各种收藏信息，但无法获取歌单和下载音频。敢问是借助了 h5api.m.xiami.com 的 API 吗？  
（毕竟 www.xiami.com 和 emumo.xiami.com 的 API 都无法用了）

**Comment by VictoriaYyz** [comment]
备份歌单和收藏歌曲的时候报错了，说 connect ETIMEDOUT 203.119.169.83:443  T.T

**Comment by lljxx1** [comment]
已经没法用拉
