### ISSUE TITLE
要不就是备份不出来文件，要不就是数据错误，准备重新导出，怎么办啊，也不知道是不是解析问题

### ISSUE THREAD

**Issue by Jia-1992** [xiami2021/backup#13]
![image](https://user-images.githubusercontent.com/78725029/107198659-5c08ff00-6a30-11eb-8b38-841799de581e.png)
![image](https://user-images.githubusercontent.com/78725029/107198694-69be8480-6a30-11eb-9445-aa98bda9bc80.png)
![image](https://user-images.githubusercontent.com/78725029/107198720-72af5600-6a30-11eb-91dd-10b30730b1b2.png)

**Comment by postxiami** [comment]
没法用了
