### ISSUE TITLE
请问“批量备份收藏“功能是把虾米数据备份到哪？

### ISSUE THREAD

**Issue by jatmiuw** [xiami2021/backup#2]
存储文件夹、账号、密码分别应该怎么填？

**Comment by postxiami** [comment]
就是批量备份收藏歌曲的音频资源，填了账号密码可以备份部分下架歌曲

**Comment by NoahWongYM** [comment]
> 就是批量备份收藏歌曲的音频资源，填了账号密码可以备份部分下架歌曲

所以存储文件夹是填写本地的文件夹吗？另外如果虾米账号是用关联的淘宝账号登录，那么账号密码应该填什么呢？

**Comment by postxiami** [comment]
> > 就是批量备份收藏歌曲的音频资源，填了账号密码可以备份部分下架歌曲
> 
> 所以存储文件夹是填写本地的文件夹吗？另外如果虾米账号是用关联的淘宝账号登录，那么账号密码应该填什么呢？

这个还真不知道... 另外不填也没关系 有个创建歌单的接口虾米关掉了 等于是没法下载下架歌曲了

**Comment by NoahWongYM** [comment]
> > > 就是批量备份收藏歌曲的音频资源，填了账号密码可以备份部分下架歌曲
> > 
> > 
> > 所以存储文件夹是填写本地的文件夹吗？另外如果虾米账号是用关联的淘宝账号登录，那么账号密码应该填什么呢？
> 
> 这个还真不知道... 另外不填也没关系 有个创建歌单的接口虾米关掉了 等于是没法下载下架歌曲了

好，谢谢解答。

**Comment by postxiami** [comment]
> > > > 就是批量备份收藏歌曲的音频资源，填了账号密码可以备份部分下架歌曲
> > > 
> > > 
> > > 所以存储文件夹是填写本地的文件夹吗？另外如果虾米账号是用关联的淘宝账号登录，那么账号密码应该填什么呢？
> > 
> > 
> > 这个还真不知道... 另外不填也没关系 有个创建歌单的接口虾米关掉了 等于是没法下载下架歌曲了
> 
> 好，谢谢解答。

今天看了下，如果你提供账号密码，恢了的歌曲也是可以下载的
