### ISSUE TITLE
求助-win系统 

### ISSUE THREAD

**Issue by MinorIndie** [xiami2021/backup#3]
大神你好，
我在“批量备份收藏” 页面填写完 备份文件夹和账号密码后，点击“开始备份”无响应。查看备份状态，速度显示null。
请问这种情况有什么解决办法吗？

![image](https://user-images.githubusercontent.com/75433061/106708826-786efb00-662e-11eb-842c-af744fb7b0de.png)

![image](https://user-images.githubusercontent.com/75433061/106708669-3d6cc780-662e-11eb-9d1f-5848c26fe5f6.png)

感谢！

**Comment by MinorIndie** [comment]
错误提示
![image](https://user-images.githubusercontent.com/75433061/106765408-bc382380-6673-11eb-828b-70e0dcabb4c0.png)

**Comment by postxiami** [comment]
你可能开了全局代理 然后访问xiami的服务器太慢了可能是这样

**Comment by z-jingjie** [comment]
@xiami2021 
MacOS Catalina，v0.0.6.dmg
已经关掉了VPN，进行直连，点击“开始备份”无响应，过一段时间后发现这个log：
>[{
	"type": "runDownloadTask",
	"error": "FetchError: request to https://h5api.m.xiami.com/h5/mtop.alimusic.music.songservice.getsongdetail/1.0/?t=1612413587014&appKey=23649156&sign=[redacted]&data={"requestStr":"{\"header\":{\"appId\":\"200\",\"platformId\":\"h5\"},\"model\":{\"songId\":\"1\"}}"} failed, reason: connect ENETDOWN 203.119.169.141:443 - Local (10.0.0.8:60256)"
}]

请问要如何处理？

**Comment by postxiami** [comment]
无法访问虾米的服务器 换个网络试试
