### ISSUE TITLE
请问作者前辈可否出点击收藏歌单查看歌单内含全部歌曲条目的功能

### ISSUE THREAD

**Issue by Koumo-OS** [xiami2021/backup#6]
请问作者前辈可否出一个在软件内的备份数据界面点击收藏歌单查看该歌单内含全部歌曲条目的功能，虽然导出的「backup.json」里面有相关数据，但是查看起来实在是太麻烦了，如果能点击该歌单名称/该歌单行的某个按钮可以展开/跳转显示歌单详细就好了，例如点击后展开/跳转像「song」界面这种条目![2021-02-05_180010](https://user-images.githubusercontent.com/49365204/107018941-06d4af80-67dc-11eb-9d05-82a4096982e9.png)

哪怕不能在软件内出一个查看的功能，也希望能导出成更易查看的表格
![2021-02-05_175757](https://user-images.githubusercontent.com/49365204/107018727-c70dc800-67db-11eb-9946-169966ef832b.png)

最后拜谢作者前辈，网易云歌单收藏数量上限真的太烦了，感谢作者的努力(๑•̀ㅂ•́)و✧

**Comment by Koumo-OS** [comment]
还有就是请问能否在抓取时将收藏的歌单/歌曲/专辑/作者/用户的图片一并抓取缓存在本地，我看json里面用的还是虾米的pic地址，如果能加上歌单查看内含歌曲以及缓存收藏的相关图片的话，那就基本上形成一个观感不错的本地虾米了

**Comment by postxiami** [comment]
https://github.com/xiami2021/visualization/blob/main/backup.html

代码开源的
