### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by jj-a-li** [xiami2021/backup#7]
启动弹错
图已更新

**Comment by jj-a-li** [comment]
![Uploading IMG_20210206_132129.jpg…]()

**Comment by postxiami** [comment]
你的图看不到

**Comment by jj-a-li** [comment]
![Uploading IMG_20210206_132129.jpg…]()

**Comment by jj-a-li** [comment]
> 你的图看不到

![Uploading IMG_20210206_154425.jpg…]()

**Comment by jj-a-li** [comment]
![IMG_20210206_154425](https://user-images.githubusercontent.com/72844255/107112518-2f6bb080-6893-11eb-86e7-148ce99c45a1.jpg)

**Comment by jj-a-li** [comment]
![IMG_20210206_154425](https://user-images.githubusercontent.com/72844255/107112530-4ad6bb80-6893-11eb-821b-b0052fd46ce0.jpg)

**Comment by jj-a-li** [comment]
> 你的图看不到

![IMG_20210206_154425](https://user-images.githubusercontent.com/72844255/107112546-6c37a780-6893-11eb-8761-7e3cebda7737.jpg)
