### ISSUE TITLE
数据备份弹出页面显示空白正常吗？

### ISSUE THREAD

**Issue by latinisation** [xiami2021/backup#8]
![image](https://user-images.githubusercontent.com/26472091/107114865-0acc0480-68a4-11eb-9fd0-dbe1e7791e07.png)
如图，请问这样是在正常工作吗？

**Comment by postxiami** [comment]
不正常

**Comment by postxiami** [comment]
防火墙什么的都关了试试

**Comment by latinisation** [comment]
> 不正常

好的谢谢

**Comment by latinisation** [comment]
> 不正常

好的谢谢
